os:
 - linux
sudo: required
dist: xenial
language: go
go:
 - "1.16"
 - master
env:
- GO111MODULE=on
services:
 - docker
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libsystemd-dev libc6-dev-arm64-cross gcc-aarch64-linux-gnu
install:
 - mkdir -p $HOME/gopath/src/k8s.io
 - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/node-problem-detector
 - cd $HOME/gopath/src/k8s.io/node-problem-detector
script:
 - make . 2> /dev/null
 - make test . 2> /dev/null
 - make clean && BUILD_TAGS="disable_custom_plugin_monitor" make . 2> /dev/null
 - BUILD_TAGS="disable_custom_plugin_monitor" make test . 2> /dev/null
 - make clean && BUILD_TAGS="disable_system_log_monitor" make . 2> /dev/null
 - BUILD_TAGS="disable_system_log_monitor" make test . 2> /dev/null
 - make clean && BUILD_TAGS="disable_system_stats_monitor" make . 2> /dev/null
 - BUILD_TAGS="disable_system_stats_monitor" make test . 2> /dev/null
 - make clean && BUILD_TAGS="disable_stackdriver_exporter" make . 2> /dev/null
 - BUILD_TAGS="disable_stackdriver_exporter" make test . 2> /dev/null
 - make clean && ENABLE_JOURNALD=0 make . 2> /dev/null
 - ENABLE_JOURNALD=0 make test . 2> /dev/null
 - ENABLE_JOURNALD=0 make build-binaries . 2> /dev/null
